[build]
  command = "npm run build"
  publish = "dist"

[secrets_scanning]
  omit_keys = [
    "VITE_EMAILJS_PUBLIC_KEY",
    "VITE_EMAILJS_SERVICE_ID",
    "VITE_EMAILJS_TEMPLATE_ID",
    "VITE_EMAILJS_QUOTATION_TEMPLATE_ID"
  ]

